In [73]:
import findspark
findspark.init()

import pyspark
from pyspark import SparkContext, SparkConf

from collections import defaultdict
from collections import Counter
import re

import importlib
from scripts import cleaners, genhelpers
importlib.reload(cleaners)
importlib.reload(genhelpers)

In [2]:
from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName('vrn_analysis') \
    .master('local[*]') \
    .getOrCreate()

sc = spark.sparkContext

# conf = SparkConf().setAppName('vrn_analysis') \
#                   .setMaster('local')
# sc = SparkContext(conf=conf)

In [3]:
data = sc.textFile('vrn.csv')

## Data Preparation

### Car identification

Steps:
1. **Clean** input data
    - Take special care to clean entries containing commas in the model name, i.e. remove those commas
    - Correct other erroneous typos
1. Obtain **list of unique car make/model combinations**
1. **De-duplicate** any similar-but-different make/model combinations
    - e.g. "C180 AVG" and "C180 AVANTGARDE"

In [5]:
car_types = data.map(lambda x: genhelpers.clean_raw_data(x)) \
                .flatMap(lambda x: x.split(',')) \
                .filter(lambda x: genhelpers.is_car_detail(x)) \
                .map(lambda x: x.strip('"'))

At this point, `car_types` is a list of car details with the structure `<make> / <model>`. <br>
e.g. "*MERCEDES BENZ / S320L (R19 LED)*"

Build a `cars` dict:

- `{ <car_make>: [<list_of_car_models>] }`

In [6]:
# line 1: clean model name
# line 2: split into (make, model) tuple
# line 3: for each make, combine all of its models into a comma-separated string
# line 4: convert comma-separated string to a list
# line 5: sort list of models in alphabetical order
# line 6: sort overall dict by make in alphabetical order
car_dict = car_types.map(lambda x: cleaners.clean_model_name(x)) \
                    .map(lambda x: x.split(' / ')) \
                    .reduceByKey(lambda x, y: x + ',' + y) \
                    .map(lambda x: (x[0], x[1].split(','))) \
                    .map(lambda x: (x[0], sorted(set(x[1])))) \
                    .sortByKey(lambda x: x[0]) \
                    .collectAsMap()

car_dict

{'ALPINA': ['B3 BITURBO'],
 'ASTON MARTIN': ['DB11 V8', 'DB9', 'RAPIDE 6.0', 'V8 VANTAGE S/SHIFT 4.7'],
 'AUDI': ['A3 SEDAN 1.0',
  'A3 SPORTBACK 1.0',
  'A5 SPORTBACK 2.0',
  'A8L 4.2',
  'Q2 1.4',
  'Q5 2.0',
  'Q5 SPORT 2.0',
  'Q7 2.0',
  'Q7 3.0',
  'R8 5.2',
  'S4 3.0'],
 'B.M.W.': ['216D ACTIVE TOURER',
  '216I GRAN TOURER',
  '216I GRAN TOURER M-SPORT',
  '218I CONVERTIBLE',
  '325I COUPE',
  '335I COUPE',
  '420I CONVERTIBLE',
  '420I COUPE M-SPORT',
  '430I COUPE M-SPORT',
  '520D M-SPORT',
  '520I',
  '523I',
  '528I',
  '530I',
  '530I M-SPORT',
  '535I',
  '540I M-SPORT',
  '630I',
  '640I',
  '640I GRAN COUPE',
  '640I GRAN COUPE M-SPORT',
  '730LI',
  '740LI',
  'I8',
  'M3 COUPE',
  'M3 SEDAN',
  'M4 COUPE',
  'M5',
  'M5 30 JAHRE EDITION',
  'M6 COUPE',
  'M6 GRAN COUPE',
  'X2 SDRIVE18I M-SPORT',
  'X3 SDRIVE20I',
  'X3 XDRIVE20I',
  'X3 XDRIVE30I M-SPORT',
  'X5 M-SPORT',
  'X5 XLINE',
  'X6 XDRIVE35I',
  'X7 XDRIVE40I'],
 'BENTLEY': ['BENTAYGA V8',
  'CONTINENTAL GT SPEED 6.0',
  'CONTINENTAL GT V8',
  'CONTINENTAL GT W12',
  'CONTINENTAL GT W12 CONVERTIBLE',
  'FLYING SPUR 6.0',
  'FLYING SPUR V8 4.0',
  'MULSANNE SPEED 6.8',
  'NEW FLYING SPUR W12'],
 'CITROEN': ['GRAND C4 PICASSO 1.6 BLUEHDI', 'GRAND C4 PICASSO 1.6 THP'],
 'FERRARI': ['458 ITALIA 4.5',
  '458 SPECIALE',
  '488 GTB',
  '488 PISTA',
  '488 SPIDER',
  'CALIFORNIA 4.3',
  'F430',
  'PORTOFINO'],
 'FORD': ['MUSTANG CONVERTIBLE 2.3'],
 'HONDA': ['ACCORD EURO R 2.0',
  'CIVIC 1.5 TURBO',
  'CIVIC 1.8',
  'HRV 1.5 LX',
  'JAZZ 1.3',
  'JAZZ 1.5',
  'ODYSSEY 2.4',
  'ODYSSEY 2.4 NAVI RES',
  'VEZEL HYBRID 1.5'],
 'HUMMER': ['H3 3.7'],
 'INFINITI': ['Q60 2.0 COUPE', 'QX80 5.6'],
 'JAGUAR': ['E-PACE 2.0', 'F-PACE R-SPORT 3.0', 'XJ 2.0'],
 'JEEP': ['GRAND CHEROKEE 6.4', 'WRANGLER UNLIMITED SAHARA'],
 'KIA': ['FORTE K3 1.6'],
 'LAMBORGHINI': ['AVENTADOR LP700-4',
  'AVENTADOR S',
  'GALLARDO LP550-2',
  'HURACAN LP610-4',
  'HURACAN PERFORMANTE',
  'URUS'],
 'LAND ROVER': ['DISCOVERY 3.0 HSE',
  'DISCOVERY SPORT 2.0 SI4 SE',
  'RANGE ROVER 3.0',
  'RANGE ROVER 4.4 SDV8',
  'RANGE ROVER EVOQUE 2.0',
  'RANGE ROVER EVOQUE CONVERTIBLE 2.0 SI4',
  'RANGE ROVER SPORT 3.0 SDV6',
  'RANGE ROVER VELAR 2.0 SI4'],
 'MASERATI': ['GHIBLI',
  'GHIBLI GRANSPORT',
  'GRANTURISMO 4.2',
  'GRANTURISMO SPORT',
  'LEVANTE 3.0 V6',
  'LEVANTE S GRANSPORT',
  'QUATTROPORTE'],
 'MAZDA': ['CX-3 2.0 DELUXE',
  'MAZDA3 1.5 M-HYBRID ASTINA',
  'MAZDA6 SEDAN 2.0 EXECUTIVE',
  'ROADSTER 1.5'],
 'MCLAREN': ['600LT', '650S SPIDER', '720S COUPE'],
 'MERCEDES BENZ': ['300SL-24',
  'A200 AMG',
  'A200 SALOON PROGRESSIVE',
  'A250 AMG SALOON',
  'A45 AMG 4MATIC',
  'AMG GT',
  'AMG GT C ROADSTER',
  'AMG GT63 S 4MATIC',
  'C180 AVANTGARDE',
  'C180 COUPE',
  'C200 AMG',
  'C200 M-HYBRID SPORT',
  'C63 AMG',
  'CLA180 AMG',
  'CLA180 COUPE',
  'CLA200 COUPE',
  'CLS 63 AMG COUPE',
  'CLS350 COUPE',
  'CLS450 4MATIC COUPE',
  'E200 AVANTGARDE',
  'E200 COUPE',
  'E200 EXCLUSIVE',
  'E220D AMG',
  'E250 AVANTGARDE',
  'E300 AMG CABRIOLET',
  'E300 EXCLUSIVE',
  'E320 AVANTGARDE',
  'E63 AMG S 4MATIC+',
  'GLA180',
  'GLA180 AMG',
  'GLC250 4MATIC',
  'GLC250 4MATIC COUPE',
  'GLC250 AMG 4MATIC',
  'GLC250 AMG 4MATIC COUPE',
  'GLE43 AMG 4MATIC COUPE',
  'GLE450 4MATIC',
  'GLS350D 4MATIC',
  'GLS400 4MATIC',
  'MAYBACH S650',
  'R280L',
  'S320L',
  'S350L',
  'S400 HYBRID',
  'S400L',
  'S450L',
  'SLC180',
  'SLS AMG COUPE'],
 'MINI': ['COOPER 1.6 3DR',
  'COOPER S CABRIOLET 1.6',
  'COOPER S CLUBMAN',
  'COOPER S CONVERTIBLE 1.6',
  'JCW COUNTRYMAN',
  'ONE 5DR'],
 'MITSUBISHI': ['EVO IX GT', 'EVO X GSR'],
 'NISSAN': ['GT-R 3.8', 'SKYLINE 2.5'],
 'PEUGEOT': ['RCZ 1.6 TURBO'],
 'PORSCHE': ['718 BOXSTER',
  '718 CAYMAN',
  '718 CAYMAN GTS',
  '911 CARRERA',
  '911 CARRERA 4S CABRIOLET',
  '911 CARRERA CABRIOLET',
  '911 CARRERA GTS',
  '911 CARRERA S',
  '911 GT2 RS',
  '911 GT3',
  '911 GT3 RS',
  '911 R',
  '911 TURBO CABRIOLET',
  'CAYENNE',
  'CAYENNE GTS',
  'CAYENNE S',
  'CAYMAN S',
  'MACAN II',
  'MACAN S II',
  'PANAMERA',
  'PANAMERA 4 E-HYBRID EXECUTIVE',
  'PANAMERA 4 EXECUTIVE',
  'PANAMERA 4S',
  'PANAMERA TURBO EXECUTIVE'],
 'RENAULT': ['MEGANE RS'],
 'ROLLS ROYCE': ['CULLINAN',
  'DAWN',
  'GHOST',
  'GHOST EWB',
  'PHANTOM',
  'PHANTOM DROPHEAD',
  'PHANTOM EWB',
  'WRAITH'],
 'RUF': ['3800S'],
 'SEAT': ['TARRACO XCELLENCE', 'TOLEDO'],
 'SKODA': ['KODIAQ LAURIN&KLEMENT'],
 'SUBARU': ['FORESTER 2.0I-S EYESIGHT HYBRID AWD CVT'],
 'SUZUKI': ['SWIFT 1.0'],
 'TOYOTA': ['ALPHARD 2.5 ELEGANCE',
  'ALPHARD 2.5 S',
  'ALPHARD 2.5 S-A',
  'ALPHARD 2.5 S-C',
  'ALPHARD 3.5 S-C',
  'ALPHARD 3.5 SA-C',
  'C-HR HYBRID 1.8G',
  'C-HR HYBRID 1.8S',
  'CAMRY 2.4',
  'COROLLA ALTIS 1.6',
  'ESTIMA 2.4 X',
  'ESTIMA HYBRID 2.4 X',
  'HARRIER G GRADE',
  'HARRIER M GRADE',
  'LEXUS ES250 EXECUTIVE',
  'LEXUS ES250 LUXURY',
  'LEXUS ES300H LUXURY',
  'LEXUS GS350 LUXURY',
  'LEXUS IS300 EXECUTIVE',
  'LEXUS LC500',
  'LEXUS NX300 LUXURY',
  'LEXUS RX200T',
  'LEXUS RX200T LUXURY',
  'LEXUS RX270',
  'LEXUS RX350',
  'LEXUS RX450H',
  'PREVIA',
  'RUSH 1.5G',
  'SUPRA RZ COUPE',
  'VELLFIRE 2.4 Z',
  'VELLFIRE 2.5 ELEGANCE',
  'VELLFIRE 2.5 X',
  'VELLFIRE 2.5 Z G-EDITION',
  'VELLFIRE 3.5 Z G-EDITION',
  'VIOS 1.5E'],
 'VOLKSWAGEN': ['GOLF 1.4', 'SHARAN 2.0', 'TOURAN 1.4'],
 'VOLVO': ['S90 T5 MOMENTUM', 'V60 T4', 'XC60 T5', 'XC60 T6 R-DESIGN']}

`car_dict` lists all of the unique car make/model combinations.

Find the corresponding price for all of the combinations.

### Car pricing

Load the CSV of car prices. This CSV contains 3 columns - "Make", "Model", "Price".

Car pricelists:
https://www.sgcarmart.com/new_cars/newcars_pricelist_listing.php

In [9]:
prices_csv = sc.textFile('data/prices.csv')

In [10]:
def split_into_3tuple(line):
    details, price = line.strip('"').split('"')
    make, model = details.strip(',').split(',')
    return (make, model, price)

prices = prices_csv.filter(lambda x: x != 'Make,Model,Price') \
                   .map(lambda x: split_into_3tuple(x)) \
                   .map(lambda x: (f'{x[0]} / {x[1]}', x[2])) \
                   .collectAsMap()

`prices` is a mapping dict of `{ <make / model>: <price> }`,<br>
e.g. "*B.M.W. / M5 30 JAHRE EDITION: 588,800*"

### Mapping cars to their corresponding price

In [67]:
def car_details_to_price(details_row):
    """Replaces the car details in a row of data with their corresponding price.
    
    Args:
        details_row (str): A row in the raw data
    """
    
    def _remove_first_col(row: str) -> list:
        row_split = row.split(',')
        return [c for i, c in enumerate(row_split) if i != 0]
    
    details_row = _remove_first_col(details_row)
    output = [genhelpers.get_price(details) for details in details_row]
    return output

In [68]:
data_with_prices = data.map(lambda x: genhelpers.clean_raw_data(x)) \
                       .filter(lambda x: remove_first_col(x)) \
                       .map(lambda x: car_details_to_price(x))

data_with_prices.collect()

[['1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '18',
  '28',
  '88',
  '99',
  '100',
  '888',
  '999',
  '8888'],
 [399888.0,
  250088.0,
  428800.0,
  504888.0,
  252888.0,
  102000.0,
  520000.0,
  102000.0,
  125000.0,
  233800.0,
  273988.0,
  1160000.0,
  1216000.0,
  343488.0,
  868000.0,
  433988.0,
  912000.0,
  0],
 [1190000.0,
  115900.0,
  912000.0,
  157000.0,
  370388.0,
  224888.0,
  82999.0,
  360000.0,
  635888.0,
  0,
  215000.0,
  912000.0,
  272888.0,
  461888.0,
  202888.0,
  246888.0,
  1468888.0,
  399888.0],
 [1297000.0,
  414888.0,
  1105000.0,
  298888.0,
  249888.0,
  798000.0,
  182888.0,
  399888.0,
  1494000.0,
  210888.0,
  572599.0,
  461888.0,
  423888.0,
  399888.0,
  242888.0,
  1468888.0,
  285888.0,
  0],
 [0,
  1160000.0,
  278788.0,
  233800.0,
  200888.0,
  912000.0,
  0,
  274888.0,
  437888.0,
  251888.0,
  769788.0,
  140776.0,
  256888.0,
  590000.0,
  0,
  136999.0,
  297800.0,
  205800.0],
 [558188.0,
  440888.0,
  380800.0,
  0,
  393999.0,
  188800.0,
  236888.0,
  555000.0,
  154900.0,
  207999.0,
  124388.0,
  240888.0,
  123999.0,
  250088.0,
  177888.0,
  98900.0,
  0,
  286888.0],
 [920000.0,
  180999.0,
  992000.0,
  456688.0,
  1494000.0,
  995000.0,
  0,
  620888.0,
  186000.0,
  148000.0,
  399888.0,
  256888.0,
  245000.0,
  287800.0,
  129999.0,
  518800.0,
  0,
  273999.0],
 [1200000.0,
  746888.0,
  207888.0,
  273988.0,
  905000.0,
  293888.0,
  987888.0,
  0,
  987888.0,
  226988.0,
  566888.0,
  378785.0,
  295000.0,
  530800.0,
  175000.0,
  426088.0,
  353888.0,
  2194000.0],
 [200000.0,
  261888.0,
  375888.0,
  307400.0,
  304999.0,
  192000.0,
  456088.0,
  318800.0,
  880000.0,
  358888.0,
  207999.0,
  250088.0,
  151999.0,
  305000.0,
  272888.0,
  307800.0,
  200000.0,
  249888.0],
 [504888.0,
  1588000.0,
  287999.0,
  192888.0,
  1588000.0,
  650000.0,
  1297000.0,
  799000.0,
  476888.0,
  450888.0,
  1201688.0,
  225888.0,
  461888.0,
  998000.0,
  0,
  192000.0,
  92888.0,
  245888.0],
 [798000.0,
  813088.0,
  252888.0,
  110000.0,
  1160000.0,
  141888.0,
  158888.0,
  363999.0,
  1268888.0,
  1160000.0,
  783380.0,
  250088.0,
  249888.0,
  1091000.0,
  182888.0,
  224888.0,
  200000.0,
  992000.0],
 [0,
  249888.0,
  252000.0,
  640888.0,
  437888.0,
  386800.0,
  992000.0,
  2194000.0,
  274888.0,
  107000.0,
  399888.0,
  647788.0,
  154999.0,
  300888.0,
  278800.0,
  1091000.0,
  272888.0,
  136460.0],
 [1490000.0,
  1150000.0,
  998000.0,
  0,
  546588.0,
  166888.0,
  0,
  1498000.0,
  298888.0,
  90999.0,
  182888.0,
  192000.0,
  740000.0,
  210888.0,
  242888.0,
  329888.0,
  180888.0,
  257888.0],
 [288788.0,
  0,
  0,
  918000.0,
  0,
  157888.0,
  995000.0,
  246888.0,
  0,
  182888.0,
  225888.0,
  345888.0,
  969000.0,
  154888.0,
  0,
  76888.0,
  295000.0,
  1091000.0],
 [1600000.0,
  671688.0,
  200000.0,
  817088.0,
  504888.0,
  489800.0,
  920000.0,
  1091000.0,
  464888.0,
  0,
  1268888.0,
  343488.0,
  124388.0,
  154999.0,
  314888.0,
  226999.0,
  304999.0,
  207888.0],
 [583188.0,
  222800.0,
  464888.0,
  0,
  157888.0,
  1600000.0,
  1160000.0,
  819688.0,
  399888.0,
  109388.0,
  109388.0,
  272888.0,
  798000.0,
  250888.0,
  249888.0,
  109999.0,
  285888.0,
  1268888.0],
 [1494000.0,
  0,
  1160000.0,
  199900.0,
  330000.0,
  164000.0,
  585888.0,
  241200.0,
  0,
  300888.0,
  798000.0,
  224888.0,
  0,
  225888.0,
  201300.0,
  0,
  90000.0,
  890000.0],
 [399888.0,
  154888.0,
  272888.0,
  898000.0,
  498800.0,
  252888.0,
  96999.0,
  192000.0,
  249888.0,
  195999.0,
  249888.0,
  163888.0,
  240888.0,
  163888.0,
  173888.0,
  225888.0,
  110000.0,
  400888.0],
 [230888.0,
  798000.0,
  217888.0,
  363999.0,
  325000.0,
  0,
  0,
  225888.0,
  912000.0,
  912000.0,
  307800.0,
  182888.0,
  393999.0,
  590000.0,
  213888.0,
  192000.0,
  0,
  119800.0],
 [0,
  504888.0,
  1600000.0,
  176800.0,
  0,
  325000.0,
  65000.0,
  348800.0,
  1400000.0,
  421000.0,
  240888.0,
  71900.0,
  223800.0,
  912000.0,
  257888.0,
  154999.0,
  180000.0,
  343488.0],
 [1490000.0,
  393999.0,
  0,
  798000.0,
  288788.0,
  280888.0,
  391888.0,
  590000.0,
  343488.0,
  134250.0,
  229000.0,
  142000.0,
  125988.0,
  225888.0,
  225888.0,
  0,
  157888.0,
  331788.0],
 [640888.0,
  111888.0,
  1216000.0,
  898000.0,
  177000.0,
  546588.0,
  340888.0,
  855000.0,
  338888.0,
  566888.0,
  0,
  210000.0,
  245000.0,
  750000.0,
  154888.0,
  182888.0,
  855000.0,
  204900.0],
 [0,
  0,
  671688.0,
  463888.0,
  0,
  249888.0,
  150000.0,
  798000.0,
  162888.0,
  226988.0,
  0,
  252000.0,
  1043000.0,
  590000.0,
  109999.0,
  225888.0,
  0,
  225888.0],
 [1400000.0,
  170888.0,
  162999.0,
  345888.0,
  228000.0,
  808000.0,
  224888.0,
  200000.0,
  0,
  324888.0,
  880000.0,
  855000.0,
  2194000.0,
  363800.0,
  76999.0,
  158888.0,
  165900.0,
  0],
 [568800.0,
  461888.0,
  2194000.0,
  182888.0,
  343488.0,
  207999.0,
  170000.0,
  201300.0,
  855000.0,
  0,
  160888.0,
  125388.0,
  207888.0,
  844888.0,
  463888.0,
  225888.0,
  244888.0,
  2194000.0],
 [385688.0,
  0,
  421000.0,
  154999.0,
  588800.0,
  987888.0,
  366888.0,
  0,
  0,
  192000.0,
  192000.0,
  172999.0,
  0,
  855000.0,
  252888.0,
  546588.0,
  234888.0,
  200000.0],
 [905000.0,
  0,
  1588000.0,
  172999.0,
  158000.0,
  2194000.0,
  504888.0,
  905000.0,
  992000.0,
  182888.0,
  375888.0,
  235000.0,
  242888.0,
  226988.0,
  233800.0,
  244888.0,
  192000.0,
  149888.0],
 [0,
  440888.0,
  130888.0,
  0,
  590000.0,
  2194000.0,
  162999.0,
  0,
  241200.0,
  288788.0,
  272888.0,
  123999.0,
  546588.0,
  363999.0,
  204900.0,
  2194000.0,
  170888.0,
  225888.0],
 [399888.0,
  1105000.0,
  242888.0,
  173888.0,
  568800.0,
  361300.0,
  544488.0,
  399888.0,
  0,
  0,
  343488.0,
  463888.0,
  0,
  370388.0,
  139888.0,
  0,
  282888.0,
  992000.0]]

`data_with_prices` here is a `PipelinedRDD`.

## Data Exploration

All of the cars and their corresponding prices have been found.

Now, it is possible to perform data exploration.

In [74]:
from itertools import islice
from pyspark.sql.types import FloatType, StructField, StructType

In [75]:
cols = data_with_prices.take(1)[0]
schema = StructType([StructField(c, FloatType()) for c in cols])

# remove first row as it is the header row
rdd = data_with_prices.mapPartitionsWithIndex(
        lambda idx, it: islice(it, 1, None) if idx == 0 else it)

In [76]:
df = spark.createDataFrame(rdd, schema)

In [90]:
df.filter(df['1'] != 0) \
  .describe(['1', '2', '3', '8', '88', '888', '8888']).show(truncate=10)

+-------+----------+----------+----------+----------+----------+----------+----------+
|summary|         1|         2|         3|         8|        88|       888|      8888|
+-------+----------+----------+----------+----------+----------+----------+----------+
|  count|        23|        23|        23|        23|        23|        23|        23|
|   mean|823694....|437115....|612252....|477627....|422721....|279958....|563107....|
| stddev|470683....|426685....|558894....|373606....|496717....|300123....|633686....|
|    min|  200000.0|       0.0|       0.0|       0.0|       0.0|       0.0|       0.0|
|    max| 1600000.0| 1588000.0| 2194000.0| 1498000.0| 2194000.0| 1468888.0| 2194000.0|
+-------+----------+----------+----------+----------+----------+----------+----------+